language: rust
rust:
  - stable
  - beta
  - nightly
node_js:
  - 10
  - 12
  - 14
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo test --verbose --all --exclude ledb-node
  - cd ledb-node && npm install && npm test
