language: rust
rust:
- stable
- beta
- nightly
jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
env:
  matrix:
  - TRAVIS_NODE_VERSION="10"
  - TRAVIS_NODE_VERSION="14"
before_install:
- source $HOME/.nvm/nvm.sh
- nvm install ${TRAVIS_NODE_VERSION}
- nvm use ${TRAVIS_NODE_VERSION}
script:
- cargo test --verbose --all
- cd ledb-node && npm install && npm test
