[package]
name = "docstor"
version = "0.1.0"
authors = ["Kayo Phoenix <kayo@illumium.org>"]

[dependencies]
bytes = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_cbor = "0.9"
lmdb-zero = "0.4"
liblmdb-sys = "0.2"
