[package]
name = "ledb-actix"
version = "0.1.0"
authors = ["Kayo Phoenix <kayo@illumium.org>"]

[dependencies]
serde = "1"
ledb = { path = "../ledb" }
actix = "0.7"

[dev-dependencies]
serde_derive = "1"
serde_json = "1"
futures = "0.1"
tokio = "0.1"
